### ISSUE TITLE
Problemas con incidence_rate

### ISSUE THREAD

**Issue by Deedado71** [epiverse-trace/epiCo#54]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [ ] I have the most recent version of linelist and R
 - [X ] I have found a bug
 - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Please include a brief description of the problem with a code example:
Para el codigo de incidence rate al usar el codigo con nivel 1 este me tira un error pero no dice el porque ocurre este siendo que la funcion funciona tambien con un level 0.

```r
incidence_object <- incidence(
  dates = data_tolima$fec_not,
  groups = data_tolima$cod_mun_o,
  interval = "1 epiweek"
)
incidence_rate_object <- incidence_rate(incidence_object, level = 1)
head(incidence_rate_object$counts)
```

---------

**Comment by juan-umana** [comment]
This issue is related to bugs in built-in epi_data dataset, please follow #80  for updates
