### ISSUE TITLE
Error in age_risk function

### ISSUE THREAD

**Issue by SilvRondon** [epiverse-trace/epiCo#55]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [] I have the most recent version of linelist and R
 - [ x] I have found a bug
 - [x ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Please include a brief description of the problem with a code example: 
This is the line that I run 
 age_risk_data <- age_risk(
+     age = data_ibague$edad,
+     population_pyramid = ibague_pyramid_2019,
+     gender = data_ibague$sexo, plot = TRUE
+ )

and this is the error
Error in age_risk(age = data_ibague$edad, population_pyramid = ibague_pyramid_2019,  : 
  `population_pyramid` should include gender

```r
# insert reprex here
```

---------

**Comment by juan-umana** [comment]
This issue is related to bugs in built-in epi_data dataset, please follow #80 for updates
