### ISSUE TITLE
BUG canal endemico

### ISSUE THREAD

**Issue by Deedado71** [epiverse-trace/epiCo#58]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [ ] I have the most recent version of linelist and R
 - [X ] I have found a bug
 - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Encontré un error al usar el código de municipio 73520 el cual en principio esta bien hasta que llegamos al código de canal endémico donde no encuentra incidencias en el municipio siendo que había incidencias.

```r
library(epiCo)
library(incidence)

data("epi_data")
data_event <- epi_data

data_ibague <- data_event[data_event$cod_mun_o == 73520, ]

## Building the historic incidence data

incidence_historic <- incidence(data_ibague$fec_not,
  interval = "1 epiweek"
)

observations <- sample(15:100, 52, replace = FALSE)

outlier_years <- c(2016, 2019)

ibague_endemic_chanel <- endemic_channel(
  incidence_historic = incidence_historic,
  observations = observations,
  outlier_years = outlier_years,
  plot = FALSE
)

ibague_endemic_chanel$endemic_channel_plot
```

---------

**Comment by Juanmontenegro99** [comment]
Gracias por tu comentario este era un error relacionado al issue #80 y en al issue #84, puedes seguir la actualización de esto en esos issues.
