### ISSUE TITLE
canal endémico plot

### ISSUE THREAD

**Issue by camilavargas1701** [epiverse-trace/epiCo#59]
data_ibague <- data_event[data_event$cod_mun_o == 73675, ]
cuando se cambia el código del municipio sale un error que no permite graficar
ERROR:
Error in data.frame(central = central, up_lim = up_lim, low_lim = low_lim,  : 
  arguments imply differing number of rows: 53, 52
Además: Warning messages:
1: In endemic_channel(incidence_historic = incidence_historic, observations = observations,  :
  Data prior to 2016-01-03 were not used for the endemic channel calculation.
2: In endemic_channel(incidence_historic = incidence_historic, observations = observations,  :
  Data after 2020-12-27 were not used for the endemic channel calculation.
3: In matrix(counts_historic, nrow = length(years), byrow = TRUE) :
  la longitud de los datos [261] no es un submúltiplo o múltiplo del número de filas [5] en la matriz

**Comment by Juanmontenegro99** [comment]
Gracias por tu comentario este era un error relacionado al issue #80 y en al issue #84, puedes seguir la actualización de esto en esos issues.
