### ISSUE TITLE
Demographic describe_ethnicity

### ISSUE THREAD

**Issue by roganich** [epiverse-trace/epiCo#61]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [X] I have the most recent version of linelist and R
 - [X] I have found a bug

--------

Please include a brief description of the problem with a code example:

When the output obtained of _describe_ethnicity_ still has the "\n" on the strings

```r
# insert reprex here
```

---------

**Comment by Juanmontenegro99** [comment]
Hola, este problema se está trabajando en el issue #68 allí puedes observar los avances de este bug.
