### ISSUE TITLE
Change endemic_channel plot

### ISSUE THREAD

**Issue by juan-umana** [epiverse-trace/epiCo#63]
**Is your feature request related to a problem? Please describe.**
Visualization problem

**Describe the solution you'd like**
Users report a better understanding of the endemic channel when it only displays lines (limits, and central tendency line)

**Additional context**
The endemic channel will be displayed as the one produced by the National Health Insitute: https://www.ins.gov.co/buscador-eventos/Informesdeevento/DENGUE%20PE%20VIII%202023.pdf

**Comment by Juanmontenegro99** [comment]
Change the background and add a legend
