### ISSUE TITLE
Endemic channels: Calculation of the standard deviation

### ISSUE THREAD

**Issue by oespinozah** [epiverse-trace/epiCo#96]
According to [PAHO](https://iris.paho.org/bitstream/handle/10665.2/8562/5n1a1.pdf?sequence=1&isAllowed=y), the cut-off points to determine the channels are calculated based on the geometric mean (expected value), the standard deviation and the value of the t distribution.

- $E(\mu) - t*SD(\mu)/\sqrt{n}$
- $E(\mu)$
- $E(\mu) + t*SD(\mu)/\sqrt{n}$

Where $\mu$ is a transformation of the cases and

$SD(\mu) = \sqrt{Var(\mu)}$

$Var(\mu) = \frac{1}{n} \sum (\mu - E(\mu) )^2$

[Endemic Channel function](https://github.com/epiverse-trace/epiCo/blob/main/R/endemic_channel.R) use `stats::sd(x)` to calculate standar deviation. This function is based on `stats::var(x)`.  It uses a C function which takes the arithmetic mean as the expected value

Therefore, I consider recommending that within the code to determine the endemic channels, the variance (and therefore, the standard deviation) be calculated in such a way that uses the geometric mean as the expected value. In other words, a function could be added to calculate it

**Comment by juan-umana** [comment]
Hi @oespinozah! Thank you for the report! We fix the issue in the PR #102. Your feedback would be very useful before we merge it to the main branch.

You can install the new version by running
install.packages("pak")
pak::pak("epiverse-trace/epiCo@96-endemic-channels-calculation-of-the-standard-deviation")

Let us know if solution looks good to you and feel confident to submit new issues. Thank you so much!

**Comment by juan-umana** [comment]
Issue was solved in PR #102
